# Generated by Django 4.1.5 on 2023-03-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "led1_status",
                    models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
                ),
                (
                    "led2_status",
                    models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
                ),
                (
                    "led3_status",
                    models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
                ),
            ],
        ),
    ]
